**Objetivo:** repetir con un dataset diferente las operaciones vistas con Pingüinos: explorar, seleccionar, filtrar, agrupar, limpiar, transformar y exportar.

**Importante:** usa el material de referencia, documentación y, si lo deseas, un asistente de IA. Debes **entender y comprobar** el código. Las celdas están intencionadamente sin resolver.

## Preparación
Este archivo usa una copia didáctica del dataset Iris con **8 celdas vacías introducidas para practicar limpieza**. Son 150 flores, tres especies y cuatro mediciones. Los datos originales se guardan en `iris_original.csv` para comparar.

Coloca este notebook en la misma carpeta que los archivos CSV. Si aparece `FileNotFoundError`, revisa la carpeta abierta en VS Code.

In [5]:
import pandas as pd

iris = pd.read_csv("iris_con_faltantes.csv")
print("Dataset cargado:", iris.shape)
display(iris.head(3))

Dataset cargado: (150, 5)

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa

**Comprobación esperada:** `(150, 5)`.

**Referencia de columnas:** `sepal_length_cm`, `sepal_width_cm`, `petal_length_cm`, `petal_width_cm`, `species`. Las medidas están expresadas en centímetros.

## Ejercicio 1. Explorar el dataset

a) Muestra las primeras cinco filas. b) Identifica las dimensiones. c) Consulta los tipos de columna y sus valores no nulos. d) Encuentra cuáles especies aparecen en la columna `species`.

**Pista:** Recuerda `head`, `shape`, `info` y `unique`. Debes encontrar **3 especies**.

In [6]:
# a) Mostrar las primeras cinco filas
print("a) Primeras 5 filas:")
display(iris.head(5))

# b) Identificar las dimensiones
print("\nb) Dimensiones (filas, columnas):", iris.shape)

# c) Consultar tipos de columna y valores no nulos
print("\nc) Información del dataset:")
iris.info()

# d) Encontrar las especies únicas en la columna 'species'
print("\nd) Especies únicas:", iris["species"].unique())

a) Primeras 5 filas:

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             NaN              1.4             0.2  setosa

b) Dimensiones (filas, columnas): (150, 5)

c) Información del dataset:
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sepal_length_cm  150 non-null    float64
 1   sepal_width_cm   145 non-null    float64
 2   petal_length_cm  150 non-null    float64
 3   petal_width_cm   147 non-null    float64
 4   species          150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

d) Especies únicas: <StringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

## Ejercicio 2. Seleccionar columnas y posiciones

a) Crea una tabla que contenga solo `species` y `petal_length_cm`. b) Muestra **las cinco primeras filas y las dos primeras columnas** mediante posiciones, no nombres.

**Pista:** Usa una lista de columnas para (a) y `iloc` para (b). El final de un slice no se incluye.

In [7]:
# a) Tabla solo con 'species' y 'petal_length_cm'
tabla_especie_petalo = iris[["species", "petal_length_cm"]]
print("a) Selección por nombres de columna:")
display(tabla_especie_petalo.head())

# b) Cinco primeras filas y dos primeras columnas por posición (iloc)
print("\nb) Primeras 5 filas y 2 primeras columnas (iloc):")
display(iris.iloc[0:5, 0:2])

a) Selección por nombres de columna:

  species  petal_length_cm
0  setosa              1.4
1  setosa              1.4
2  setosa              1.3
3  setosa              1.5
4  setosa              1.4

b) Primeras 5 filas y 2 primeras columnas (iloc):

   sepal_length_cm  sepal_width_cm
0              5.1             3.5
1              4.9             3.0
2              4.7             3.2
3              4.6             3.1
4              5.0             NaN

## Ejercicio 3. Filtrar con una o dos condiciones

a) Selecciona solamente flores de la especie `setosa`. b) Selecciona flores de `virginica` cuyo `petal_length_cm` sea **mayor que 5.5**. c) Muestra cuántas filas tiene cada resultado.

**Pista:** Utiliza una máscara de comparación y `&`; cada condición debe ir entre paréntesis.

In [8]:
# a) Flores de la especie 'setosa'
filtro_setosa = iris[iris["species"] == "setosa"]

# b) Flores de 'virginica' con 'petal_length_cm' > 5.5
filtro_virginica = iris[(iris["species"] == "virginica") & (iris["petal_length_cm"] > 5.5)]

# c) Mostrar cuántas filas tiene cada resultado
print("c) Cantidad de flores setosa:", len(filtro_setosa))
print("c) Cantidad de flores virginica con pétalo > 5.5 cm:", len(filtro_virginica))

c) Cantidad de flores setosa: 50
c) Cantidad de flores virginica con pétalo > 5.5 cm: 25

## Ejercicio 4. Contar y agrupar por especie

a) Cuenta cuántas flores hay de cada especie. b) Calcula el **promedio de `petal_length_cm` para cada especie**. c) Identifica cuál tiene el promedio mayor.

**Pista:** Busca `value_counts`, `groupby` y `mean`. La columna `petal_length_cm` no contiene faltantes en esta copia.

In [9]:
# a) Contar cuántas flores hay de cada especie
print("a) Conteo por especie:")
print(iris["species"].value_counts())

# b) Promedio de 'petal_length_cm' para cada especie
promedios_petalo = iris.groupby("species")["petal_length_cm"].mean()
print("\nb) Promedio de petal_length_cm por especie:")
print(promedios_petalo)

# c) Identificar cuál tiene el promedio mayor
especie_mayor = promedios_petalo.idxmax()
valor_mayor = promedios_petalo.max()
print(f"\nc) La especie con mayor promedio es '{especie_mayor}' ({valor_mayor:.2f} cm)")

a) Conteo por especie:
species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

b) Promedio de petal_length_cm por especie:
species
setosa        1.462
versicolor    4.260
virginica     5.552
Name: petal_length_cm, dtype: float64

c) La especie con mayor promedio es 'virginica' (5.55 cm)

## Ejercicio 5. Limpiar valores faltantes y quitar columnas

a) Cuenta cuántos valores faltan por columna. b) Crea **una copia** sin las filas que tengan valores vacíos y cuenta cuántas quedan. c) Crea otra copia donde rellenes únicamente los faltantes de `sepal_width_cm` con su mediana. d) Crea una tercera copia sin la columna `petal_width_cm`. **No modifiques `iris` directamente.**

**Pista:** Recuerda `isna().sum()`, `dropna()`, `fillna()`, `median()` y `drop(columns=[...])`. Esperamos **142 filas completas** antes de rellenar.

In [10]:
# a) Contar cuántos valores faltan por columna
print("a) Valores faltantes por columna:")
print(iris.isna().sum())

# b) Copia sin filas con valores vacíos y contar cuántas quedan
iris_sin_nulos = iris.dropna().copy()
print("\nb) Filas completas restantes tras dropna():", len(iris_sin_nulos))

# c) Copia rellenando faltantes de 'sepal_width_cm' con su mediana
iris_rellenado = iris.copy()
mediana_sepal = iris_rellenado["sepal_width_cm"].median()
iris_rellenado["sepal_width_cm"] = iris_rellenado["sepal_width_cm"].fillna(mediana_sepal)
print("\nc) Faltantes en 'sepal_width_cm' tras rellenar con mediana:", iris_rellenado["sepal_width_cm"].isna().sum())

# d) Tercera copia sin la columna 'petal_width_cm'
iris_sin_columna = iris.drop(columns=["petal_width_cm"]).copy()
print("\nd) Columnas en la tercera copia:", list(iris_sin_columna.columns))

a) Valores faltantes por columna:
sepal_length_cm    0
sepal_width_cm     5
petal_length_cm    0
petal_width_cm     3
species            0
dtype: int64

b) Filas completas restantes tras dropna(): 142

c) Faltantes en 'sepal_width_cm' tras rellenar con mediana: 0

d) Columnas en la tercera copia: ['sepal_length_cm', 'sepal_width_cm', 'petal_length_cm', 'species']

## Ejercicio 6. Transformar columnas

a) Crea en una copia una nueva columna `petal_length_mm` convirtiendo centímetros a milímetros. b) Crea otra columna `species_codigo` asignando `S`, `V` y `G` a las tres especies. c) Comprueba cinco filas.

**Pista:** Para la conversión basta una operación sobre toda la columna; para códigos puedes usar `.map()` con un diccionario. Si quieres, prueba también `.apply(lambda ...)`.

In [11]:
# Crear copia para trabajar
iris_transformado = iris.copy()

# a) Nueva columna 'petal_length_mm' (1 cm = 10 mm)
iris_transformado["petal_length_mm"] = iris_transformado["petal_length_cm"] * 10

# b) Nueva columna 'species_codigo' asignando S, V y G
mapa_codigos = {
    "setosa": "S",
    "versicolor": "V",
    "virginica": "G"
}
iris_transformado["species_codigo"] = iris_transformado["species"].map(mapa_codigos)

# c) Comprobar cinco filas
print("c) Comprobación de 5 filas del DataFrame transformado:")
display(iris_transformado.head(5))

c) Comprobación de 5 filas del DataFrame transformado:

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species,petal_length_mm,species_codigo
0,5.1,3.5,1.4,0.2,setosa,14.0,S
1,4.9,3.0,1.4,0.2,setosa,14.0,S
2,4.7,3.2,1.3,0.2,setosa,13.0,S
3,4.6,3.1,1.5,0.2,setosa,15.0,S
4,5.0,NaN,1.4,0.2,setosa,14.0,S

## Ejercicio 7. Exportar el resultado

a) Guarda el DataFrame transformado del ejercicio 6 en `iris_procesado.csv`, **sin guardar la columna de índice**. b) Vuelve a leer el CSV con Pandas y comprueba que conserva 150 filas y las nuevas columnas.

**Pista:** Usa `to_csv` con `index=False` y después `read_csv`.

In [12]:
# a) Guardar el DataFrame transformado del ejercicio 6 sin columna de índice
iris_transformado.to_csv("iris_procesado.csv", index=False)
print("a) Archivo 'iris_procesado.csv' guardado correctamente.")

# b) Volver a leer el CSV y comprobar filas y columnas
iris_leido = pd.read_csv("iris_procesado.csv")
print("\nb) Dimensiones del archivo leído:", iris_leido.shape)
display(iris_leido.head(3))

a) Archivo 'iris_procesado.csv' guardado correctamente.

b) Dimensiones del archivo leído: (150, 7)

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species,petal_length_mm,species_codigo
0,5.1,3.5,1.4,0.2,setosa,14.0,S
1,4.9,3.0,1.4,0.2,setosa,14.0,S
2,4.7,3.2,1.3,0.2,setosa,13.0,S

## Ejercicio 8. Unir filas con `concat`

a) Construye dos DataFrames: primeras 50 filas y siguientes 50 filas de `iris`. b) Únelos verticalmente y comprueba el número total de filas.

**Pista:** Combina `iloc` y `pd.concat`; prueba `ignore_index=True`.

In [13]:
# a) Construir dos DataFrames: primeras 50 filas y siguientes 50 filas
parte_1 = iris.iloc[0:50]
parte_2 = iris.iloc[50:100]

# b) Unirlos verticalmente y comprobar el número total de filas
iris_unido = pd.concat([parte_1, parte_2], ignore_index=True)
print("b) Dimensiones tras unir con concat:", iris_unido.shape)
print("Total de filas:", len(iris_unido))

b) Dimensiones tras unir con concat: (100, 5)
Total de filas: 100

## Ejercicio 9. Relacionar tablas con `merge`
Crea una tabla pequeña con las columnas `species` y `codigo`: setosa→S, versicolor→V y virginica→G. Une esta tabla con `iris` mediante la especie. Verifica que aparecen 150 filas y una columna adicional. Los códigos son solamente etiquetas didácticas.

**Pista:** Puedes construir la tabla auxiliar con `pd.DataFrame({...})` y hacer un `merge` por `species`.

In [14]:
# Crear tabla auxiliar con 'species' y 'codigo'
tabla_codigos = pd.DataFrame({
    "species": ["setosa", "versicolor", "virginica"],
    "codigo": ["S", "V", "G"]
})

# Unir esta tabla con 'iris' mediante la columna 'species'
iris_merge = pd.merge(iris, tabla_codigos, on="species")

# Verificar que aparecen 150 filas y una columna adicional (6 en total)
print("Dimensiones tras el merge:", iris_merge.shape)
display(iris_merge.head(5))

Dimensiones tras el merge: (150, 6)

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species,codigo
0,5.1,3.5,1.4,0.2,setosa,S
1,4.9,3.0,1.4,0.2,setosa,S
2,4.7,3.2,1.3,0.2,setosa,S
3,4.6,3.1,1.5,0.2,setosa,S
4,5.0,NaN,1.4,0.2,setosa,S

## Antes de entregar
**Guarde en un Github creado Público** `git status` → `git add .` → `git commit -m "Practicar consultas y transformaciones con Pandas"`. Evita subir al repositorio archivos de entornos virtuales (`.venv/`).